# Generated by Django 3.1 on 2020-08-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
