# Generated by Django 3.1 on 2020-08-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0003_newuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
    ]
