# Generated by Django 3.1 on 2020-08-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0004_auto_20200825_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='nickname'),
        ),
    ]
