# Generated by Django 3.1 on 2020-08-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0006_auto_20200825_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='gender',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
