# Generated by Django 3.1 on 2020-08-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='birth',
            field=models.DateTimeField(null=True, verbose_name='birthday'),
        ),
    ]
